### ISSUE TITLE
ng2 create init serve fails

### ISSUE THREAD

**Issue by kaefert** [madhusudhand/angular2-cli#13]
My development machine is an Ubuntu 16.04.1 LTS (xenial xerus)

I installed nodejs including npm on it as desribed here:
http://www.angulartypescript.com/angular-typescript-npm-linux/

which gave me nodejs v6.9.2 and npm v3.10.9

I then went on and installed angular2-cli as described here: https://www.npmjs.com/package/angular2-cli
`npm install -g angular2-cli`

and went on with the instructions of that page and ran
```
ng2 create angular2-demo
cd angular2-demo
ng2 init
ng2 serve
```

which sadly only results in a webpage displaying "Loading...." forever and these errors output in the console:
[angular2-demo-serve-error.txt](https://github.com/madhusudhand/angular2-cli/files/656875/angular2-demo-serve-error.txt)

summary: as far as I understand it it complains that it `Cannot read property 'exclude' of undefined` of the files `src/main.ts` & `src/vendor.ts`

did I do something wrong or is there something broken?

**Comment by madhusudhand** [comment]
looks like cli has broken.
Please try https://www.npmjs.com/package/angular-cli

**Comment by kaefert** [comment]
ah okey. yes that worked.
```
npm install -g angular-cli
ng new angular2-demo
cd angular2-demo
ng serve
```
thanks :)

**Comment by kaefert** [comment]
I don't think it's appropriate to close this issue of this project because there exists another project that can do what this one at the moment can't although it seems to have been designed to do it too.

(maybe my assessment is wrong, I'm just starting getting into angular2)
